### ISSUE TITLE
Vault registering

### ISSUE THREAD

**Issue by zRich** [zRich/fusion#10]
User Story:
Alice is an end user, Bob is a service provide. 
Alice wants Bob host her vault. 
Bob needs to register Alice's vault. 
Once Bob completed registering, Alice can save data into her vault and query data from it.

**Comment by zRich** [comment]
[Vault Registering RFC](https://github.com/bytehubplus/fusion-rfcs/blob/main/rfc/rfc-002-vault-registering.md)

**Comment by EricZequan** [comment]
1. Bob registers a service locally with gin to receive the DID and related documents sent by Alice.

2. Alice sends her DID and the document corresponding to DID to Bob, and the message needs to be encrypted with Bob's public key.

3. After receiving the message, Bob decrypts the message with his own private key and obtains Alice's public key after the decryption is completed.

4. Bob takes Alice's public key as the parameter of RegisterVault() and returns the generated Vault ID.
